FROM instructure/node-passenger:latest

ENV APP_HOME /usr/src/app

USER root

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
RUN chown -R docker:docker $APP_HOME
COPY . $APP_HOME
WORKDIR $APP_HOME
RUN npm install
RUN ["bash", "-c", "shopt -s extglob dotglob\nchown -R docker:docker $APP_HOME/!(node_modules)"]